# -*- coding: utf-8 -*-
"""Untitled26.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TfTLG1O-TKoRi9wDqs-sTafxbeHpRho3
"""

import pandas as pd
import numpy as np
import os
import glob
import joblib
import lightgbm as lgb
from sklearn.model_selection import train_test_split

print("========== 🏆 啟動【LambdaRank 排序演算法】高階訓練系統 ==========")

# 1. 掛載硬碟與設定路徑

# 直接抓取同一個資料夾底下的模型檔
MODEL_PATH = 'my_hkjc_ranker.pkl'


# 2. 自動搜尋所有歷史 CSV 檔案
search_patterns = ["hkjc_data_*.csv", "hkjc_full_season_*.csv"]
all_files = []
for pattern in search_patterns:
    all_files.extend(glob.glob(pattern))

if not all_files:
    print("⚠️ 找不到歷史 CSV 檔案。")
else:
    print(f"📂 讀取 {len(all_files)} 個檔案中...")
    df_list = []
    for f in all_files:
        try:
            temp_df = pd.read_csv(f, encoding='utf-8-sig', on_bad_lines='skip')
        except UnicodeDecodeError:
            temp_df = pd.read_csv(f, encoding='cp950', on_bad_lines='skip')
        df_list.append(temp_df)

    df = pd.concat(df_list, ignore_index=True)

    # 3. 資料清洗
    df['獨贏賠率'] = pd.to_numeric(df['獨贏賠率'], errors='coerce')
    df = df[(df['獨贏賠率'] > 1.0) & (df['名次'].notna())].copy()

    # 🎯 核心改變 1：建立「排序權重 (Relevance)」
    # 讓 AI 知道：贏馬最重要(3分)，第二名次之(2分)，第三名也有價值(1分)，落第(0分)
    df['numeric_rank'] = pd.to_numeric(df['名次'], errors='coerce').fillna(99)
    df['relevance'] = 0
    df.loc[df['numeric_rank'] == 1, 'relevance'] = 3
    df.loc[df['numeric_rank'] == 2, 'relevance'] = 2
    df.loc[df['numeric_rank'] == 3, 'relevance'] = 1

    # 計算基本特徵 (15大)
    if '騎師' in df.columns:
        jockey_stats = df.groupby('騎師', observed=False)['numeric_rank'].apply(lambda x: (x==1).mean()).reset_index(name='jockey_win_rate')
        df = pd.merge(df, jockey_stats, on='騎師', how='left')
    df['jockey_win_rate'] = df.get('jockey_win_rate', pd.Series(0.12, index=df.index)).fillna(0.12)

    if '練馬師' in df.columns:
        trainer_stats = df.groupby('練馬師', observed=False)['numeric_rank'].apply(lambda x: (x==1).mean()).reset_index(name='trainer_win_rate')
        df = pd.merge(df, trainer_stats, on='練馬師', how='left')
    df['trainer_win_rate'] = df.get('trainer_win_rate', pd.Series(0.12, index=df.index)).fillna(0.12)

    df['combo_win_rate'] = (df['jockey_win_rate'] + df['trainer_win_rate']) / 2
    df['horse_win_rate'] = 0.10
    df['horse_last_rank'] = 6.0

    if '馬名' in df.columns and '場地' in df.columns:
        surface_stats = df.groupby(['馬名', '場地'], observed=False)['numeric_rank'].apply(lambda x: (x==1).mean()).reset_index(name='horse_surface_win_rate')
        df = pd.merge(df, surface_stats, on=['馬名', '場地'], how='left')
    df['horse_surface_win_rate'] = df.get('horse_surface_win_rate', pd.Series(0.08, index=df.index)).fillna(0.08)

    if '馬名' in df.columns and '距離' in df.columns:
        df['dist_group'] = pd.cut(df['距離'], bins=[0, 1200, 1600, 2400], labels=['短途', '中途', '長途'])
        dist_stats = df.groupby(['馬名', 'dist_group'], observed=False)['numeric_rank'].apply(lambda x: (x==1).mean()).reset_index(name='horse_dist_win_rate')
        df = pd.merge(df, dist_stats, on=['馬名', 'dist_group'], how='left')
    df['horse_dist_win_rate'] = df.get('horse_dist_win_rate', pd.Series(0.08, index=df.index)).fillna(0.08)

    df['market_prob'] = 1 / df['獨贏賠率']
    prob_sum = df.groupby('賽事編號')['market_prob'].transform('sum')
    df['market_implied_prob'] = df['market_prob'] / prob_sum

    df['odds_rank'] = df.groupby('賽事編號')['獨贏賠率'].rank(method='min')
    df['is_favorite'] = (df['odds_rank'] == 1).astype(int)
    df['排位檔位'] = pd.to_numeric(df['排位檔位'], errors='coerce').fillna(7)

    if '距離' not in df.columns: df['距離'] = 1200
    df['實際負磅'] = pd.to_numeric(df.get('實際負磅', 120), errors='coerce').fillna(120.0)
    avg_weight = df.groupby('賽事編號')['實際負磅'].transform('mean')
    df['weight_diff'] = df['實際負磅'] - avg_weight
    df['weight_rank'] = df.groupby('賽事編號')['實際負磅'].rank(ascending=False, method='min')

    feature_cols = [
        'market_implied_prob', '獨贏賠率', 'odds_rank', 'is_favorite',
        '排位檔位', 'weight_diff', 'weight_rank',
        'jockey_win_rate', 'trainer_win_rate', 'combo_win_rate',
        'horse_win_rate', 'horse_last_rank',
        '距離', 'horse_surface_win_rate', 'horse_dist_win_rate'
    ]

    for col in feature_cols:
        if col not in df.columns: df[col] = 0.0

    # 🎯 核心改變 2：絕對不能打亂賽事，必須以「整場比賽」為單位進行切割
    unique_races = df['賽事編號'].unique()
    train_races, val_races = train_test_split(unique_races, test_size=0.2, random_state=42)

    # 將資料按照賽事編號嚴格排序 (LambdaRank 必備條件)
    train_df = df[df['賽事編號'].isin(train_races)].sort_values('賽事編號')
    val_df = df[df['賽事編號'].isin(val_races)].sort_values('賽事編號')

    X_train = train_df[feature_cols]
    y_train = train_df['relevance']
    group_train = train_df.groupby('賽事編號').size().values  # 告訴 AI 每一場有幾匹馬

    X_val = val_df[feature_cols]
    y_val = val_df['relevance']
    group_val = val_df.groupby('賽事編號').size().values

    print(f"🚀 開始訓練【LambdaRank 模型】(訓練集包含 {len(train_races)} 場賽事)...")

    # 🎯 核心改變 3：改用 LGBMRanker
    model = lgb.LGBMRanker(
        objective="lambdarank",
        metric="ndcg",         # NDCG 是一種專門評估「排序準不準」的分數
        n_estimators=300,
        learning_rate=0.03,
        max_depth=6,
        random_state=42
    )

    model.fit(
        X_train, y_train,
        group=group_train,
        eval_set=[(X_val, y_val)],
        eval_group=[group_val],
        callbacks=[lgb.early_stopping(stopping_rounds=25, verbose=False)]
    )

    print(f"\n📊 訓練大功告成！LambdaRank 的邏輯已建立。")

    # 4. 儲存模型 (另存新檔，不覆蓋原本的分類模型)
    model_filename = 'my_hkjc_ranker.pkl'
    joblib.dump(model, model_filename)
    print(f"\n💾 排序模型已成功儲存為：{model_filename}")

import streamlit as st
import pandas as pd
import numpy as np
import os
import joblib

# 頁面基本設定
st.set_page_config(
    page_title="HKJC LambdaRank 賽馬預測系統",
    page_icon="🏆",
    layout="wide"
)

st.title("🏆 HKJC LambdaRank 智能排序系統")
st.markdown("---")

# 🎯 這裡改為讀取最新的排序模型
MODEL_PATH = 'my_hkjc_ranker.pkl'

@st.cache_resource
def load_model():
    if os.path.exists(MODEL_PATH):
        return joblib.load(MODEL_PATH)
    return None

model = load_model()

if model is None:
    st.error(f"⚠️ 找不到 AI 模型檔 `{MODEL_PATH}`！請確認是否已成功生成。")
    st.stop()

st.sidebar.header("📂 資料載入")
uploaded_file = st.sidebar.file_uploader("請上傳賽事資料 (CSV)", type=['csv'])

st.sidebar.markdown("---")
st.sidebar.header("⚙️ 投注策略參數")
min_ev = st.sidebar.slider("最小期望值 (EV)", 0.0, 1.5, 0.0, 0.05)
min_odds = st.sidebar.number_input("最低獨贏賠率", min_value=1.0, max_value=50.0, value=3.0)
max_odds = st.sidebar.number_input("最高獨贏賠率", min_value=1.0, max_value=100.0, value=30.0)

if uploaded_file is not None:
    try:
        df_raw = pd.read_csv(uploaded_file, encoding='utf-8-sig')
    except:
        uploaded_file.seek(0)
        df_raw = pd.read_csv(uploaded_file, encoding='cp950')

    st.success("✅ 賽事資料載入成功！")

    st.subheader("⚡ 快速輸入臨場賠率 (支援手機直接點擊修改)")
    st.info("👇 點擊下方表格的『獨贏賠率』欄位即可修改數字。修改後，AI 會自動重新排序！")

    edit_columns = ['賽事編號', '馬號', '馬名', '排位檔位', '獨贏賠率']
    df_editable = df_raw[edit_columns].copy()

    edited_df = st.data_editor(
        df_editable,
        disabled=['賽事編號', '馬號', '馬名', '排位檔位'],
        use_container_width=True,
        hide_index=True
    )

    df = df_raw.copy()
    df['獨贏賠率'] = pd.to_numeric(edited_df['獨贏賠率'], errors='coerce').fillna(10.0)

    # 1. 特徵工程
    df['market_prob'] = 1 / df['獨贏賠率']
    prob_sum = df.groupby('賽事編號')['market_prob'].transform('sum')
    df['market_implied_prob'] = df['market_prob'] / prob_sum

    df['odds_rank'] = df.groupby('賽事編號')['獨贏賠率'].rank(method='min')
    df['is_favorite'] = (df['odds_rank'] == 1).astype(int)
    df['排位檔位'] = pd.to_numeric(df['排位檔位'], errors='coerce').fillna(7)

    if '實際負磅' in df.columns:
        df['實際負磅'] = pd.to_numeric(df['實際負磅'], errors='coerce').fillna(120)
        avg_weight = df.groupby('賽事編號')['實際負磅'].transform('mean')
        df['weight_diff'] = df['實際負磅'] - avg_weight
        df['weight_rank'] = df.groupby('賽事編號')['實際負磅'].rank(ascending=False, method='min')
    else:
        df['weight_diff'] = 0.0
        df['weight_rank'] = 6.0

    df['numeric_rank'] = pd.to_numeric(df.get('名次', 99), errors='coerce').fillna(99)
    df['jockey_win_rate'] = df.get('jockey_win_rate', 0.12)
    df['trainer_win_rate'] = df.get('trainer_win_rate', 0.12)
    df['combo_win_rate'] = df.get('combo_win_rate', 0.10)
    df['horse_win_rate'] = df.get('horse_win_rate', 0.10)
    df['horse_last_rank'] = df.get('horse_last_rank', 6.0)

    if '距離' not in df.columns: df['距離'] = 1200
    if 'horse_surface_win_rate' not in df.columns: df['horse_surface_win_rate'] = 0.08
    if 'horse_dist_win_rate' not in df.columns: df['horse_dist_win_rate'] = 0.08

    feature_cols = [
        'market_implied_prob', '獨贏賠率', 'odds_rank', 'is_favorite',
        '排位檔位', 'weight_diff', 'weight_rank',
        'jockey_win_rate', 'trainer_win_rate', 'combo_win_rate',
        'horse_win_rate', 'horse_last_rank',
        '距離', 'horse_surface_win_rate', 'horse_dist_win_rate'
    ]

    for col in feature_cols:
        if col not in df.columns: df[col] = 0.0

    X_predict = df[feature_cols].fillna(0)

    # 🎯 核心升級：使用 predict 取得 LambdaRank 的實力分數
    df['raw_score'] = model.predict(X_predict)

    # 🎯 將實力分數轉換為相對勝率 (Softmax 演算法)
    def softmax(x):
        e_x = np.exp(x - np.max(x))
        return e_x / e_x.sum()

    df['pred_win_prob'] = df.groupby('賽事編號')['raw_score'].transform(softmax)

    # 計算 EV
    df['ev'] = df['pred_win_prob'] * df['獨贏賠率']

    st.markdown("---")
    tab1, tab2 = st.tabs(["🎯 排序預測推薦", "📈 歷史回測 (ROI 統計)"])

    with tab1:
        st.subheader("🎯 LambdaRank 排序推薦清單")

        recommendations = []
        for race_id, group in df.groupby('賽事編號'):
            # 使用模型給出的分數 (raw_score) 或 EV 來排序
            filtered_group = group[(group['ev'] >= min_ev) & (group['獨贏賠率'] >= min_odds) & (group['獨贏賠率'] <= max_odds)]
            sorted_group = filtered_group.sort_values(by='raw_score', ascending=False).reset_index(drop=True)

            if len(sorted_group) >= 2:
                top1 = sorted_group.iloc[0]
                top2 = sorted_group.iloc[1]
                top3 = sorted_group.iloc[2] if len(sorted_group) >= 3 else top2

                win_pick = f"馬號 {top1['馬號']} ({top1['馬名']}) [相對勝率:{top1['pred_win_prob']*100:.1f}%, EV:{top1['ev']:.2f}]"
                q_pick = f"{top1['馬號']} + {top2['馬號']}"
                qp_pick = f"{top1['馬號']} + {top2['馬號']} / {top3['馬號']}"

                recommendations.append({
                    '賽事編號': race_id,
                    '🎯 首選獨贏': win_pick,
                    '🔗 Q / QP': q_pick + " | " + qp_pick
                })

        rec_df = pd.DataFrame(recommendations)
        if rec_df.empty:
            st.warning("⚠️ 沒有符合當前 EV 或賠率門檻的馬匹。")
        else:
            st.dataframe(rec_df, use_container_width=True)

    with tab2:
        st.subheader("📊 排序模型策略回測結果 (專業對帳單)")
        
        # 防呆檢查：確認有沒有真實名次
        if (df['numeric_rank'] == 99).all():
            st.info("💡 目前上傳的資料沒有真實名次，無法計算 ROI。請上傳包含完賽名次的歷史資料檔來執行回測。")
        else:
            total_invested = 0
            total_return = 0
            bet_count = 0
            win_count = 0
            backtest_records = []
            
            BET_AMOUNT = 100  # 每場固定投注 100 元
            current_bankroll = 0  # 追蹤累積盈虧水位
            
            for race_id, group in df.groupby('賽事編號'):
                filtered_group = group[(group['ev'] >= min_ev) & (group['獨贏賠率'] >= min_odds) & (group['獨贏賠率'] <= max_odds)]
                sorted_group = filtered_group.sort_values(by='raw_score', ascending=False).reset_index(drop=True)
                
                if len(sorted_group) > 0:
                    top1 = sorted_group.iloc[0]
                    bet_count += 1
                    total_invested += BET_AMOUNT
                    
                    is_win = (top1['numeric_rank'] == 1)
                    if is_win:
                        win_count += 1
                        payout = BET_AMOUNT * top1['獨贏賠率']
                        result_str = "✅ 命中"
                    else:
                        payout = 0
                        result_str = "❌ 落空"
                        
                    net_profit = payout - BET_AMOUNT
                    current_bankroll += net_profit
                    total_return += payout
                    
                    # 抓取 AI 的次選與三選，觀察其真實完賽名次 (對玩 Q / QP 極具參考價值)
                    top2_info = f"馬號 {sorted_group.iloc[1]['馬號']} (跑第 {int(sorted_group.iloc[1]['numeric_rank'])} 名)" if len(sorted_group) > 1 else "-"
                    top3_info = f"馬號 {sorted_group.iloc[2]['馬號']} (跑第 {int(sorted_group.iloc[2]['numeric_rank'])} 名)" if len(sorted_group) > 2 else "-"
                    
                    backtest_records.append({
                        '賽事編號': race_id,
                        '🎯 首選馬 (獨贏)': f"馬號 {top1['馬號']} ({top1['馬名']})",
                        '預測勝率': f"{top1['pred_win_prob']*100:.1f}%",
                        '期望值 (EV)': top1['ev'],
                        '賠率': top1['獨贏賠率'],
                        '實際名次': int(top1['numeric_rank']) if top1['numeric_rank'] != 99 else "未知",
                        '結果': result_str,
                        '淨盈虧': net_profit,
                        '累積盈虧': current_bankroll,
                        '🥈 次選馬表現': top2_info,
                        '🥉 三選馬表現': top3_info
                    })
            
            if bet_count > 0:
                roi = ((total_return - total_invested) / total_invested) * 100
                
                # 1. 頂部指標儀表板
                col1, col2, col3, col4 = st.columns(4)
                col1.metric("投注場數", f"{bet_count} 場")
                col2.metric("實際命中", f"{win_count} 場", f"勝率: {win_count/bet_count*100:.1f}%")
                col3.metric("總成本", f"${total_invested}")
                col4.metric("總回收", f"${total_return:.1f}", f"ROI: {roi:.2f}%")
                
                st.markdown("---")
                
                res_df = pd.DataFrame(backtest_records)
                
                # 2. 資金水位走勢圖 (Equity Curve)
                st.markdown("#### 📈 累積盈虧走勢圖 (Bankroll Equity Curve)")
                chart_data = res_df[['賽事編號', '累積盈虧']].set_index('賽事編號')
                st.line_chart(chart_data)
                
                st.markdown("#### 📝 賽事詳細對帳單")
                
                # 3. 數據表上色邏輯 (贏錢標綠，輸錢標紅)
                def color_result(val):
                    if val == '✅ 命中': return 'color: #00FF00; font-weight: bold;'
                    elif val == '❌ 落空': return 'color: #FF4B4B;'
                    return ''
                    
                def color_profit(val):
                    if isinstance(val, (int, float)):
                        if val > 0: return 'color: #00FF00; font-weight: bold;'
                        elif val < 0: return 'color: #FF4B4B;'
                    return ''

                # 套用顏色並格式化小數點與金錢符號
                try:
                    # Pandas 2.1.0 以上使用 map
                    styled_df = res_df.style.map(color_result, subset=['結果']) \
                                            .map(color_profit, subset=['淨盈虧', '累積盈虧']) \
                                            .format({"期望值 (EV)": "{:.2f}", "賠率": "{:.1f}", "淨盈虧": "${:.1f}", "累積盈虧": "${:.1f}"})
                except AttributeError:
                    # 相容舊版 Pandas
                    styled_df = res_df.style.applymap(color_result, subset=['結果']) \
                                            .applymap(color_profit, subset=['淨盈虧', '累積盈虧']) \
                                            .format({"期望值 (EV)": "{:.2f}", "賠率": "{:.1f}", "淨盈虧": "${:.1f}", "累積盈虧": "${:.1f}"})
                
                st.dataframe(styled_df, use_container_width=True)
                
            else:
                st.info("💡 在目前的 EV 和賠率篩選條件下，沒有任何場次符合出手標準。")
